### ISSUE TITLE
Store adviser statistics on successfull reports provided to user to be reported to maintainers and managers

### ISSUE THREAD

**Issue by pacospace** [thoth-station/reporter#173]
**Is your feature request related to a problem? Please describe.**
Advise report should provide more insights on adviser service.

**Describe the solution you'd like**
Add adviser statistics on reports/products provided to users and number of failures, highlighting specific justifications:
- CPU (https://github.com/thoth-station/thoth-station.github.io/blob/master/_j/cpu_time_exceeded.md)
- no stack (https://thoth-station.ninja/j/no_stack)
- OOM (https://github.com/thoth-station/thoth-station.github.io/blob/master/_j/oom.md)

tasks:
- [x] Extend thoth-report processing to handle justifitications statistics
- [x] Create statistics to be stored on Ceph as required by SLO-reporter

**Describe alternatives you've considered**

**Additional context**

**Comment by fridex** [comment]
A failure in the resolution based on an unsolved package(s) could be also considered.

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> Advise report should provide more insights on adviser service.
> 
> **Describe the solution you'd like**
> Add adviser statistics on reports/products provided to users and number of failures, highlighting specific justifications:
> 
> * CPU (https://github.com/thoth-station/thoth-station.github.io/blob/master/_j/cpu_time_exceeded.md)
> * timeout (https://thoth-station.ninja/j/no_stack)
> * OOM (https://github.com/thoth-station/thoth-station.github.io/blob/master/_j/oom.md)

* unresolved package (https://github.com/thoth-station/thoth-station.github.io/blob/master/_j/unresolved.md)
> 
> tasks:
> 
> * [ ]  Extend thoth-report processing to handle justifitications statistics
> * [ ]  Create statistics to be stored on Ceph as required by SLO-reporter
> 
> post-tasks:
> 
> * [ ]  Add logic in SLO-reporter
> 
> **Describe alternatives you've considered**
> 
> **Additional context**

**Comment by pacospace** [comment]
![Adviser quality analysis](https://user-images.githubusercontent.com/27498679/114762529-26e79880-9d62-11eb-98ad-81a4744d8552.png)

**Comment by pacospace** [comment]
show all errors in the email. so team is aware, for example https://thoth-station.ninja/j/solve_direct -> increase learning rate
